sudo: true
language: c
os: linux

dist: trusty

before_script:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq || true
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y --force-yes gcc-arm-none-eabi
  - arm-none-eabi-gcc --version

script:
  - make -C libopencm3 TARGETS=stm32/f4
  - make
